function histload(hist_in, latetime)

% Loads pressure and temperature values for monitored nodes over time.
%SYNTAX
%   histload(hist_in) reads data from .hist file (or structure generated by
%   gethist()), generates plots of temperature and pressure over time, as
%   well as differential plots for each.
%
%   histchk(hist_in, latetime) truncates output plots, showing only a final
%   fraction of data (e.g., .5 shows the last half, .2 the last fifth).
%
%EXAMPLE
%   histchk('grid_2.hist');
%
%   histchk('120_5perm2.hist', .5);
%
%   histchk(hisStruct, .3);
%
%   See also GETFIN, GETPROP, GETAVS.
%
%   Based on histchk by Dustin Winslow, UCSC Hydrogeology
%   Revision: 0.9 , 2021/02/08

if nargin<2
    latetime=1;
end

if nargin<1
    disp('Locating .hist file...')
    hist_in=getfile('*.hist');
end

if ischar(hist_in)
    his=gethist(hist_in);
else
    his=hist_in;
end
clearvars hist_in

nnode=size(his.temperature,2);
nodestr=num2cell(his.node);
nodestr=cellfun(@num2str,nodestr,'UniformOutput',0);

ind1 = floor(length(his.time).*(1-latetime));
if ind1 < 1; ind1 = 1; end
if ind1 >= length(his.time) - 1; ind1 = length(his.time) - 2; end

lateind=ind1:length(his.time);

delT=diff(his.temperature(lateind,:));
delP=diff(his.total_pressure(lateind,:));
delt=repmat(his.deltime(lateind(1:end-1)),1,nnode);
time=repmat(his.time(lateind(1:end)),1,nnode);
timeD=repmat(his.time(lateind(2:end)),1,nnode);

figure(1)
subplot(2,1,1)
plot(time./365,his.temperature(lateind,:),'.');
xlabel('Time (years)')
ylabel('Temperature (degC)')
legend(nodestr,'Location','NorthEastOutside')

subplot(2,1,2)
plot(time./365,his.total_pressure(lateind,:),'.');
xlabel('Time (years)')
ylabel('Pressure (MPa)')
legend(nodestr,'Location','NorthEastOutside')
legend('hide')

figure(2)
subplot(2,1,1)
plot(timeD./365,365.*1000.*delT./delt,'.')
xlabel('Time (years)')
ylabel('Temperature difference (degC/kyr)')
legend(nodestr,'Location','NorthEastOutside')

subplot(2,1,2)
plot(timeD./365,365.*1000.*1000.*delP./delt,'.')
xlabel('Time (years)')
ylabel('Pressure difference (kPa/kyr)')
legend(nodestr,'Location','NorthEastOutside')
legend('hide')

keyboard

end

